name: user_starter
description: "Users App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  logger: ^2.5.0
  http: ^1.2.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/images/google.svg
    - lib/images/facebook.svg
    - lib/images/x_twitter.svg
